name: prometeu

services:
  web:
    image: nginx:latest
    ports: 
      - '9090:80'

    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - ./www:/var/www/html
  db:
    build:
      context: ./mysql

    restart: always

    volumes:
      - db_data:/var/lib/mysql 
      - ./mysql/databasebackups/databases:/docker-entrypoint-initdb.d

    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: Prometeudb

  backend:
    build:
      context: ./php/
    volumes:
      - ./www:/var/www/html

volumes:
  db_data:
