services:
  web:
    image: nginx:latest
    port: 
      - '9090:80'

    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read-only: true

      - type: volume
        source: ./www
        target: /usr/share/nginx/html
        read-only: true


  db:
    build:
      context: ./mysql

    volumes:
      - type: volume
        source: ./mysql/database
        target: /var/lib/mysql

    MYSQL_ROOT_PASSWORD: 12345

    MYSQL_USER: user
    MYSQL_PASSWORD: 12345

    MYSQL_DATABASE: Prometeudb
    
  backend:
    image: php:8.3-fpm



